# Render deployment configuration
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: prisma-talent-api
    env: python
    region: oregon
    plan: starter
    branch: main
    buildCommand: "pip install poetry && poetry install --without dev"
    startCommand: "poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        sync: false
      - key: FROM_EMAIL
        value: noreply@luishuayaney.com
      - key: REPLY_TO_EMAIL
        value: luis@luishuayaney.com
      - key: DEFAULT_ADMIN_EMAIL
        value: luis@luishuayaney.com
      - key: ALLOWED_ORIGINS
        value: https://prismatalent.vercel.app,http://localhost:3000,http://localhost:5173
      - key: FRONTEND_URL
        value: https://prismatalent.vercel.app
      - key: ADMIN_DASHBOARD_URL
        value: https://prismatalent.vercel.app/admin
      - key: CLIENT_PORTAL_URL
        value: https://prismatalent.vercel.app/client/dashboard
